<?php
define('AWS_API_KEY', 'AKIAISP3JZ5QKILYFVXQ');
define('AWS_API_SECRET_KEY', '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');
define('AWS_ASSOCIATE_TAG', 'mobilekraz1-20');
define('AWS_ANOTHER_ASSOCIATE_TAG', 'ANOTHER ASSOCIATE TAG');